# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationset-dynamodb-plugin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationset-dynamodb-plugin
  template:
    metadata:
      labels:
        app: applicationset-dynamodb-plugin
    spec:
      serviceAccountName: applicationset-dynamodb-plugin-serviceaccount
      containers:
      - name: applicationset-dynamodb-plugin
        imagePullPolicy: Always
        image: public.ecr.aws/tsahiduek/applicationset-dynamodb-plugin:latest
        args:
          - -debug
        # env:
        # - name: AWS_DEFAULT_REGION
        #   value: eu-west-1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
