# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: applicationset-dynamodb-plugin-service
spec:
  selector:
    app: applicationset-dynamodb-plugin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
